name: Build documentation
on: [push, workflow_dispatch]
jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Install fonts
        run: sudo apt-get install fonts-font-awesome fonts-roboto texlive-fonts-recommended texlive-fonts-extra
      - name: Typst
        uses: yusancky/setup-typst@v2
        id: setup-typst
        with:
          version: 'v0.11.0'
      - run: typst compile modern-cv-docs.typ
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: modern-cv-docs
          path: modern-cv-docs.pdf
